version: '3'
services:

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./data/mongodb:/data/db
