version: '3'

services:
  arangodb:
    image: arangodb:latest
    restart: always
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: 1234
      ARANGO_STORAGE_ENGINE: rocksdb
      ARANGO_EDITION: enterprise
    volumes:
      - ./data/arangodb3:/var/lib/arangodb3
