version: '3'
services:
  cassandra:
    image: cassandra:latest                           
    ports:                             
      - "7000:7000"                             
      - "9042:9042"                           
    volumes:                             
      - ./data/cassandra:/var/lib/cassandra
